# docker-compose.yml
version: '3.8'

services:
  # MLflow Tracking and UI Server
  mlflow:
    build: ./mlflow-server
    ports:
      - "5001:5001"  
    volumes:
      - ./mlruns:/mlruns  
    networks:
      - mlops-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 2s

  # FastAPI Application Server
  app:
    build: ./app
    ports:
      - "8000:8000" 
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    depends_on:
      mlflow: 
        condition: service_healthy
    networks:
      - mlops-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
      - prometheus-data:/prometheus 
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - mlops-network

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000" 
    volumes:
      - grafana-data:/var/lib/grafana 
    depends_on:
      - prometheus
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge

volumes:

  prometheus-data:
    driver: local
  grafana-data:
    driver: local